server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://39.106.166.126:3306/medicaldb?characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: whyHKT783.
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true